(let ((+ -)) (+ 2 1))
(let ((+ 1)) +)
(define fib (lambda (n) (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2))))))
(fib 10)
(define l (list 1 2 3))
(car l)
(cdr l)
(letrec ((even? (lambda (n) (if (= n 0) #t (odd? (- n 1)))))
         (odd? (lambda (n) (if (= n 0) #f (even? (- n 1))))))
  (even? 5))
(exit)
